# Ensemble Learning

## Initial Imports

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)
df.dropna()
# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [18]:
# Create our features
df=pd.DataFrame(np.random.randn(68817,86))            #training
msk = np.random.rand(len(df)) < 0.8
train = df[msk]
test = df[~msk]



# Create our target

In [19]:
X.describe()

,0,1,2,3,4,5,6,7,8,9,...,76,77,78,79,80,81,82,83,84,85
count,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,0.002998,-0.000287,-0.000068,0.004740,0.002057,-0.001901,0.002517,-0.000924,0.002073,0.001235,...,0.002575,-0.003636,0.007779,-0.004404,-0.000010,-0.004119,-0.003831,-0.006260,0.003319,0.006793
std,0.998788,0.997183,1.002818,1.000114,1.000731,1.003829,0.998323,1.004931,0.999133,0.997169,...,1.001099,1.001634,1.001218,0.996876,1.000791,1.001690,1.001617,0.997002,0.999305,0.998247
min,-4.226049,-3.924179,-4.032011,-4.575843,-4.267652,-3.971466,-4.099182,-3.896163,-4.457056,-4.112483,...,-4.683498,-4.236055,-3.995168,-4.187696,-4.534221,-4.107814,-4.567168,-4.085626,-3.877482,-4.063249
25%,-0.665744,-0.669588,-0.678720,-0.673186,-0.675385,-0.677354,-0.672805,-0.680531,-0.672126,-0.674722,...,-0.667492,-0.676444,-0.670283,-0.675236,-0.678674,-0.682324,-0.677460,-0.680177,-0.671855,-0.666320
50%,0.000071,-0.001970,0.002975,0.000277,0.004170,0.000871,0.002515,0.003043,0.003773,0.003581,...,0.004885,-0.003740,0.013083,-0.004725,0.003069,-0.004080,-0.004126,-0.012154,0.004929,0.009173
75%,0.671953,0.668397,0.682151,0.681161,0.677171,0.671695,0.673210,0.678669,0.674381,0.676479,...,0.675249,0.675207,0.681049,0.667956,0.675829,0.671673,0.672485,0.659021,0.678507,0.680998
max,4.847372,4.792762,4.236295,4.553559,4.378045,4.654354,4.505466,4.824719,4.576240,4.433937,...,4.204217,4.092614,4.152717,4.039088,4.329893,3.882212,4.585949,4.002520,4.382786,4.240468

In [ ]:
# Check the balance of our target values

In [ ]:
# Split the X and y into X_train, X_test, y_train, y_test

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [ ]:
# Create the StandardScaler instance
# YOUR CODE HERE

In [ ]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE

In [ ]:
# Scale the training and testing data
# YOUR CODE HERE

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [ ]:
# Resample the training data with the BalancedRandomForestClassifier
# YOUR CODE HERE

In [ ]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

In [ ]:
# Display the confusion matrix
# YOUR CODE HERE

In [ ]:
# Print the imbalanced classification report
# YOUR CODE HERE

In [ ]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE

### Easy Ensemble Classifier

In [ ]:
# Train the Classifier
# YOUR CODE HERE

In [ ]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

In [ ]:
# Display the confusion matrix
# YOUR CODE HERE

In [ ]:
# Print the imbalanced classification report
# YOUR CODE HERE

### Final Questions

1. Which model had the best balanced accuracy score?

    YOUR ANSWER HERE.

2. Which model had the best recall score?

    YOUR ANSWER HERE.

3. Which model had the best geometric mean score?

    YOUR ANSWER HERE.

4. What are the top three features?

    YOUR ANSWER HERE.